- intercept: KEY_CAPSLOCK
  ontap: KEY_ESC
  onhold:
    - {from: KEY_H, to: KEY_LEFT}
    - {from: KEY_J, to: KEY_DOWN}
    - {from: KEY_K, to: KEY_UP}
    - {from: KEY_L, to: KEY_RIGHT}

- intercept: KEY_ESC
  ontap: KEY_CAPSLOCK
